name: Deploy to telegram

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  send-to-telegram:
    name: send file to telegram
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install modules
        run: yarn

      - name: made gradle executable
        run: chmod +x ./android/gradle

      - name: generate apk
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
          cd ..

      - name: send file as message
        run: |
          cd android/app/build/outputs/apk/release/
          "curl -X POST -H 'Content-Type: multipart/form-data' -F text='App Release!' -F chat_id=$TG_CHAT_ID $TG_BOT_TOKEN/sendMessage"
          "curl -X POST -H 'Content-Type: multipart/form-data' -F document=@app-release.apk -F chat_id=$TG_CHAT_ID $TG_BOT_TOKEN/sendDocument"
