name: Deploy to telegram

on:
  workflow_dispatch: # allow jobs manual run
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker://circleci/android:api-29-node

      - name: install modules
        run: yarn

      - name: unit testing
        run: yarn test -u
